import type { RecommendationContext, RecommendationFeedbackAction } from '@/lib/exercise-recommendations';

export const db: any;
export type { RecommendationContext, RecommendationFeedback, RecommendationFeedbackAction } from '@/lib/exercise-recommendations';
export type Exercise = { id: string; name: string; area: string; mark: string; color: string; equipment: string; isFeatured: number; detailsJson: string | null };
export function getExercises(): Exercise[];
export function getFeaturedExercises(): Exercise[];
export type WorkoutSplit = 'push' | 'pull' | 'legs' | `custom:${string}`;
export type CustomSplit = { id: `custom:${string}`; name: string; muscles: string[] };
export function getCustomSplits(): CustomSplit[];
export function saveCustomSplit(split: { id?: CustomSplit['id']; name: string; muscles: string[] }): CustomSplit;
export function deleteCustomSplit(id: CustomSplit['id']): void;
export function getWorkoutSplitDefinition(split: WorkoutSplit): { id: string; name: string; muscles: string[] } | null;
export function getRecommendedWorkoutSplit(now?: Date): WorkoutSplit;
export type Workout = { id: string; split: WorkoutSplit; createdAt: Date; endedAt: Date | null };
export function createWorkout(split: WorkoutSplit): Workout;
export function saveWorkoutSet(set: { exerciseId: string; workoutId: string; setNumber: number; weight: number; reps: number; completedAt: Date }): void;
export function closeExpiredWorkouts(now?: Date): number;
export function getActiveWorkout(): Workout | null;
export function endWorkout(workoutId: string): Workout | null;
export type WorkoutVisitSummary = { workout: Workout; sets: number; exercises: number; volume: number; reps: number };
export function getWorkoutVisitSummary(workoutId: string): WorkoutVisitSummary | null;
export type WorkoutVisitExercise = { id: string; name: string; sets: number; volume: number };
export function getWorkoutVisitExercises(workoutId: string): WorkoutVisitExercise[];
export type WorkoutVisitExerciseDetail = { id: string; name: string; sets: { number: number; weight: number; reps: number }[] };
export function getWorkoutVisits(): WorkoutVisitSummary[];
export function getWorkoutVisitExerciseDetails(workoutId: string): WorkoutVisitExerciseDetail[];
export type WorkoutAchievement = { exerciseId: string; name: string; level: 'silver' | 'gold'; metric: 'weight' | 'reps'; weight: number; reps?: number };
export function getWorkoutAchievements(workoutId: string): WorkoutAchievement[];
export type WorkoutProgressPoint = { workoutId: string; volume: number; completedAt: Date };
export function getWorkoutProgress(workoutId: string): WorkoutProgressPoint[];
export type WorkoutMuscle = { id: string; name: string; area: string };
export type WorkoutMuscleRating = WorkoutMuscle & { exhaustion: number };
export function getWorkoutMuscles(workoutId: string): WorkoutMuscle[];
export function saveWorkoutMuscleRatings(workoutId: string, ratings: Record<string, number>): void;
export type CloudSyncTombstone = { entity: 'workout' | 'set' | 'rating' | 'split'; key: string; deletedAt: number };
export type CloudSyncEntity = 'workout' | 'set' | 'rating' | 'feedback' | 'split';
export type CloudSyncChange = { entity: CloudSyncEntity; key: string; operation: 'upsert' | 'delete'; baseRevision: number; record?: Record<string, unknown> };
export type CloudSyncRemoteChange = Omit<CloudSyncChange, 'baseRevision'> & { revision: number };
export type CloudSyncBatch = { batchId: string; changes: CloudSyncChange[] };
export function markCloudSyncDirty(entity?: CloudSyncEntity, key?: string): void;
export function hasPendingCloudSync(): boolean;
export function recordCloudSyncFailure(): void;
export function getCloudSyncBatch(limit?: number): CloudSyncBatch | null;
export function acknowledgeCloudSyncBatch(batchId: string, revision: number): void;
export function getCloudSyncCursor(): number;
export function prepareCloudSyncForUser(userId: string): void;
export function clearLocalAccountData(): void;
export function mergeCloudSyncChanges(changes: CloudSyncRemoteChange[], cursor: number): void;
export function getWorkoutMuscleRatings(workoutId: string): WorkoutMuscleRating[];
export type ExerciseRecommendation = { exercise: Exercise; reason: string; score: number; sets: number; reps: { min: number; max: number }; restSeconds: number; estimatedMinutes: number; relativeLoadPercent?: number };
export function getExerciseRecommendations(workoutId: string, split: WorkoutSplit, limit?: number, context?: RecommendationContext): ExerciseRecommendation[];
export function recordRecommendationFeedback(workoutId: string, exerciseId: string, action: RecommendationFeedbackAction, rank?: number): void;
export function getNextSetNumberForWorkout(exerciseId: string, workoutId: string): number;
export type WorkoutHistoryPoint = { workoutId: string; setNumber: number; weight: number; reps: number; completedAt: Date };
export function getWorkoutHistory(exerciseId: string): WorkoutHistoryPoint[];
export function getRecentExerciseExhaustion(exerciseId: string, excludingWorkoutId: string, now?: Date): number | undefined;
export function deleteWorkoutSet(exerciseId: string, set: WorkoutHistoryPoint): void;
export type WorkoutStats = { visits: number; sets: number; volume: number };
export function getWorkoutStats(): WorkoutStats;
export type WorkoutActivity = { date: string; volume: number; sets: number; visits: number };
export function getWorkoutActivity(days?: number): WorkoutActivity[];
export type WorkoutSplitTrend = { split: 'ALL' | 'PUSH' | 'PULL' | 'LEGS'; points: { weekStart: string; volume: number }[] };
export function getWorkoutSplitTrends(weeks?: number): WorkoutSplitTrend[];
